import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconAperture,
  IconShoppingCart,
  IconHelp,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconLayout,
  IconZoomCode,
  IconSettings,
  IconBorderStyle2,
  IconAppWindow,
  IconLockAccess,
  IconWoman,
  IconBuildingHospital,
} from '@tabler/icons';

import { uniqueId } from 'lodash';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },

  {
    id: uniqueId(),
    title: 'Doctor Dashboard',
    icon: IconBuildingHospital,
    href: '/dashboards/doctor',
    // chip: 'New',
    chipColor: 'secondary',
    userType: 'doctor',
  },
  {
    id: uniqueId(),
    title: 'Woman Dashboard',
    icon: IconWoman,
    href: '/dashboards/woman',
    userType: 'user',
  },
  {
    navlabel: true,
    subheader: 'Artificial Intelligence',
  },
  {
    id: uniqueId(),
    title: 'Ultrasound',
    icon: IconChartDonut3,
    href: '/apps/blog/',
    userType: 'doctor',
    children: [
      {
        id: uniqueId(),
        title: 'Entity Classification',
        icon: IconPoint,
        href: '/ultrasound/entity_classification',
      },
      {
        id: uniqueId(),
        title: 'Head Circumference',
        icon: IconPoint,
        href: '/ultrasound/head_circumference',
      },
      {
        id: uniqueId(),
        title: 'Report Generation',
        icon: IconPoint,
        href: '/ultrasound/report_generation',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Generator',
    icon: IconChartDonut3,
    href: '/generator/names/',
    userType: 'user',
    children: [
      {
        id: uniqueId(),
        title: 'Chat',
        icon: IconPoint,
        href: '/generator/chat',
      },
      {
        id: uniqueId(),
        title: 'Baby Names',
        icon: IconPoint,
        href: '/generator/names',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Apps',
  },
  {
    id: uniqueId(),
    title: 'Notes',
    icon: IconNotes,
    href: '/apps/notes',
    userType: 'doctor',
  },
  {
    id: uniqueId(),
    title: 'Blog',
    icon: IconChartDonut3,
    href: '/apps/blog/posts',
    userType: 'user',
  },
  {
    id: uniqueId(),
    title: 'Calendar',
    icon: IconCalendar,
    href: '/apps/calendar',
  },
  {
    id: uniqueId(),
    title: 'Tickets',
    icon: IconTicket,
    href: '/apps/tickets',
  },
  {
    navlabel: true,
    subheader: 'Pages',
  },
  {
    id: uniqueId(),
    title: 'Account Setting',
    icon: IconUserCircle,
    href: '/pages/account-settings',
  },
  {
    id: uniqueId(),
    title: 'FAQ',
    icon: IconHelp,
    href: '/pages/faq',
  },
];

export default Menuitems;
